version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: pixlon-db
    restart: 'on-failure'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: pixlon-app
    restart: 'on-failure'
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - IMAGE_UPLOAD_DIR=/app/public/uploads
    depends_on:
      - mongo
    volumes:
      - ./:/app
      

volumes:
  mongo-data:
  nextjs-images:
